### ISSUE TITLE
Issue loading newordherg_qNet model

### ISSUE THREAD

**Issue by pragathikv** [FDA/CiPA#1]
![image](https://user-images.githubusercontent.com/16655273/38438802-7015121e-3990-11e8-92d6-1ddf9d4d890c.png)
![image](https://user-images.githubusercontent.com/16655273/38438810-741efe92-3990-11e8-9949-5f73907ced01.png)
Could you please help resolve the issue or post .dll file?
Thank you!

**Comment by lzhtom** [comment]
Hi
This seems to be a compilation issue under windows. Did you install Rtools? I found many times you need Rtools to properly compile code into dll files under windows. I could share dll file with you but unless our systems have exactly the same configurations it may not work. 
Thanks!

**Comment by pragathikv** [comment]
![image](https://user-images.githubusercontent.com/16655273/38525831-a21f527c-3c08-11e8-8ae7-bf5474c2c69b.png)
![image](https://user-images.githubusercontent.com/16655273/38525868-cb71d2c6-3c08-11e8-94e1-91639e8e5654.png)
I do have Rtools installed. Infact reinstalled to check it again. Could you share dll file please?

**Comment by bridder** [comment]
Normally, we do not provide troubleshooting services for system issues. Even if we give you the .DLL file, it may not even work.

Status 127 is likely a path issue. Try the command shell("PATH") in RStudio, and see if Rtools\bin is in the output.
