### ISSUE TITLE
dyn.load error issue.

### ISSUE THREAD

**Issue by platanus-study** [FDA/CiPA#8]
>extension<-ifelse(isWindows, ".dll", ".so") 
>dyn.load(paste0("D:/platanus/CiPA_Rocde/CiPA-master/AP_simulation/models/newordherg_qNet",extension)) 

Error in inDL(x, as.logical(local), as.logical(now), ...) :
unable to load shared object 'D:/platanus/CiPA_Rocde/CiPA-master/AP_simulation/models/newordherg_qNet.dll' 
LoadLibrary failure: The specified module could not be found.

May be..... Does it occur error because of  Rtool version?

I'm using R 3.6.3 version and Rtool35 version based on window10.

**Comment by shanmdphd** [comment]
Have you successfully done `R CMD SHLIB newordherg_qNet.c` or does this error occur when you're running the command?

**Comment by platanus-study** [comment]
When I ran code - R CMD SHLIB newordherg_gNet.c' or 'R CMD SHLIB D:/platanus/CiPA_Rocde/CiPA-master/AP_simulation/models/newordherg_qNet.c  in rstudio, It occurrs error that is unpexpected in R CMD.

**Comment by platanus-study** [comment]
> Have you successfully done `R CMD SHLIB newordherg_qNet.c` or does this error occur when you're running the command?

**Comment by platanus-study** [comment]
When I ran code - R CMD SHLIB newordherg_gNet.c' or 'R CMD SHLIB D:/platanus/CiPA_Rocde/CiPA-master/AP_simulation/models/newordherg_qNet.c ' in rstudio, It occurrs error that is unpexpected symbol in R CMD.

To run R CMD SHLIB command in rstudio, What I Should do?

**Comment by platanus-study** [comment]
> > extension<-ifelse(isWindows, ".dll", ".so")
> > dyn.load(paste0("D:/platanus/CiPA_Rocde/CiPA-master/AP_simulation/models/newordherg_qNet",extension))
> 
> Error in inDL(x, as.logical(local), as.logical(now), ...) :
> unable to load shared object 'D:/platanus/CiPA_Rocde/CiPA-master/AP_simulation/models/newordherg_qNet.dll'
> LoadLibrary failure: The specified module could not be found.
> 
> May be..... Does it occurr error because of Rtool version?
> 
> I'm using R 3.6.3 version and Rtool35 version based on window10.

**Comment by platanus-study** [comment]
> > extension<-ifelse(isWindows, ".dll", ".so")
> > dyn.load(paste0("D:/platanus/CiPA_Rocde/CiPA-master/AP_simulation/models/newordherg_qNet",extension))
> 
> Error in inDL(x, as.logical(local), as.logical(now), ...) :
> unable to load shared object 'D:/platanus/CiPA_Rocde/CiPA-master/AP_simulation/models/newordherg_qNet.dll'
> LoadLibrary failure: The specified module could not be found.
> 
> May be..... Does it occurr error because of Rtool version?
> 
> I'm using R 3.6.3 version and Rtool35 version based on window10.
> 
> > Have you successfully done `R CMD SHLIB newordherg_qNet.c` or does this error occur when you're running the command?
> 
> > When I ran code - R CMD SHLIB newordherg_gNet.c' or 'R CMD SHLIB D:/platanus/CiPA_Rocde/CiPA-master/AP_simulation/models/newordherg_qNet.c ' in rstudio, It occurrs error that is unpexpected symbol in R CMD.

**Comment by platanus-study** [comment]
> When I ran code - R CMD SHLIB newordherg_gNet.c' or 'R CMD SHLIB D:/platanus/CiPA_Rocde/CiPA-master/AP_simulation/models/newordherg_qNet.c ' in rstudio, It occurrs error that is unpexpected symbol in R CMD.

**Comment by shanmdphd** [comment]
The C code should be compiled in the cmd or powershell prior to running `AP_simulation.R`. 
You have to enter the command in the 'cmd.exe' in Windows 10 ("Window key+R"). In Rstudio, you may press "Shift+Alt+R" and run the following scripts.

![image](https://user-images.githubusercontent.com/6946821/78961234-c4930100-7b2b-11ea-9faf-1503f8b6206a.png)

**Comment by platanus-study** [comment]
Thank you for answering my question. I ran the code that is 'newordherg_qNet.c' in powershell environment in window10 or terminal environment in rstudio as you have explained me above. But aftering compiling the code, It occurs another error. The error is as follow.

 
- Run error example
-------------------------------------------------------------------    
    PS D:\Platanus\CiPA_Rocde\CiPA-master\AP_simulation\models> R CMD SHLIB newordherg_qNet.c
    Invoke-History : 'SHLIB' It couldn't find location parameter permitting factor.  
    Location line : 1 character : 1
    + R CMD SHLIB newordherg_qNet.c
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-History], 
    ParameterBindingException
    + FullyQualifiedErrorId : 
 PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeHistoryCommand
 
--------------------------------------------------------------------------------------------------

Although I find solution associated with R CMD SHLIB issue, it is difficult to solve the issue. Do you have any idea to solve the error?

**Comment by platanus-study** [comment]
I already solve above problem. The error was just because of problem associated with system type in my PC. we need to confirm whether It was installed well  or not , when installing R and Rstudio and R package. If someone has above error, I'd like to recommend to reinstall  corresponding elements and reboot PC.

**Comment by platanus-study** [comment]
I already solved the problem associated with 'R CMD SHLIB'. The error was just because of problem associated with system type in my PC. We need to confirm whether it was installed well or not , when installing R, Rstudio and R package. If someone has above error, I'd like to recommend to reinstall  corresponding elements and reboot PC.

**Comment by shanmdphd** [comment]
Happy to hear it. Now you can close this issue.
